### ISSUE TITLE
Cannot find OpenLDAP build dir

### ISSUE THREAD

**Issue by drudgede** [hamano/openldap-pbkdf2#5]
Hello,

I have never worked with LDAP before and have a problem to install your plugin.
I installed the LDAP server with apt-get install slapd ldap-utils.
Now I do not find the <OPENLDAP_BUILD_DIR>/contrib/slapd-modules/passwd/ directory.
I searched my whole wystem for the slapd-modules directory but I got an empty result.
Can you give me a hint how to install it anyway?

Thank you in advance!

**Comment by hamano** [comment]
Download OpenLDAP from here:
http://www.openldap.org/software/download/
Cheer,
