### ISSUE TITLE
How to use with apt version - is it possible?

### ISSUE THREAD

**Issue by evetere-baufest** [hamano/openldap-pbkdf2#6]
Hello,
We have openldap on debian 7.x which currently installs openldap/2.4.31-1+nmu2 from apt.
We'd like to use pbkdf2 with that version.
Is it possible to build the pw-pbkdf2 module as indicated and then copy/configure the .o and .la to 2.4.31-1+nmu2?
Thanks in advance.

**Comment by hamano** [comment]
I'ts possible. You need to build from source package, through.

**Comment by ltoinel** [comment]
Did-you make working  the pw-pbkdf2 with openldap/2.4.31-1+nmu2  ?
